search bar added in countries and universites
ithqindia/metroclub pull request #100
Opened 2022-01-13 07:54 UTC by sumedh-mohod

search bar functionality added in countries and universities

2022-01-13 08:01 UTC, ithqindia requested changes

2022-01-13 08:01 UTC, ithqindia commented on app/Http/Controllers/CountryController.php
> +use App\Models\User;
Remove this

2022-01-13 08:01 UTC, ithqindia commented on app/Http/Controllers/UniversityController.php
> +use App\Models\User;
Remove this

2022-01-13 12:41 UTC, sumedh-mohod commented on app/Http/Controllers/UniversityController.php
> +use App\Models\User;
done

2022-01-13 12:42 UTC, sumedh-mohod commented
ckeditor added but not working

2022-01-14 09:29 UTC, ithqindia approved these changes

2022-01-14 12:17 UTC, ithqindia commented
Merged locally in https://github.com/ithqindia/metroclub/pull/97

2022-01-14 12:17 UTC, closed without merging