Updates/jan 17 sumedh
ithqindia/metroclub pull request #115
Opened 2022-01-17 07:36 UTC by sumedh-mohod

counselor session and session feedback done

2022-01-18 04:37 UTC, ithqindia requested changes

2022-01-18 04:37 UTC, ithqindia commented on app/Http/Controllers/CounselorSessionController.php
> +            'purpose_session' => $request->get('purpose_session'),
purpose_session -> session_purpose

2022-01-18 04:37 UTC, ithqindia commented on app/Http/Controllers/CounselorSessionController.php
> +            'purpose_session' => 'required',
purpose_session -> session_purpose

2022-01-18 04:37 UTC, ithqindia commented on app/Http/Controllers/CounselorSessionController.php
> +        $counselorSessionInformation->purpose_session = $request->get('purpose_session');
purpose_session -> session_purpose

2022-01-18 04:37 UTC, ithqindia commented on app/Http/Controllers/SessionFeedbackController.php
> +            'student_feedback' => 'required',
student_feedback -> feedback_for_student

2022-01-18 04:37 UTC, ithqindia commented on app/Http/Controllers/SessionFeedbackController.php
> +            'student_feedback' => $request->get('student_feedback'),
student_feedback -> feedback_for_student

2022-01-18 04:37 UTC, ithqindia commented on app/Http/Controllers/SessionFeedbackController.php
> +        $sessionFeedback->student_feedback = $request->get('student_feedback');
student_feedback -> feedback_for_student

2022-01-18 04:37 UTC, ithqindia commented on database/migrations/2022_01_17_085955_add_fields_to_session.php
> +            $table->string('purpose_session');
purpose_session -> session_purpose

2022-01-18 04:37 UTC, ithqindia commented on database/migrations/2022_01_17_091430_add_fields_to_student_feeedback.php
> +            $table->string('student_feedback');
student_feedback -> feedback_for_student

2022-01-18 05:55 UTC, sumedh-mohod commented on app/Http/Controllers/CounselorSessionController.php
> +            'purpose_session' => $request->get('purpose_session'),
done

2022-01-18 05:55 UTC, sumedh-mohod commented on app/Http/Controllers/CounselorSessionController.php
> +            'purpose_session' => 'required',
done

2022-01-18 05:55 UTC, sumedh-mohod commented on app/Http/Controllers/CounselorSessionController.php
> +        $counselorSessionInformation->purpose_session = $request->get('purpose_session');
done

2022-01-18 05:56 UTC, sumedh-mohod commented on app/Http/Controllers/SessionFeedbackController.php
> +            'student_feedback' => 'required',
done

2022-01-18 05:56 UTC, sumedh-mohod commented on app/Http/Controllers/SessionFeedbackController.php
> +            'student_feedback' => $request->get('student_feedback'),
done

2022-01-18 05:56 UTC, sumedh-mohod commented on app/Http/Controllers/SessionFeedbackController.php
> +        $sessionFeedback->student_feedback = $request->get('student_feedback');
done

2022-01-18 05:56 UTC, sumedh-mohod commented on database/migrations/2022_01_17_085955_add_fields_to_session.php
> +            $table->string('purpose_session');
done

2022-01-18 05:56 UTC, sumedh-mohod commented on database/migrations/2022_01_17_091430_add_fields_to_student_feeedback.php
> +            $table->string('student_feedback');
done

2022-01-18 05:56 UTC, sumedh-mohod commented
counselor form saperated and also added in frontend

2022-01-18 14:07 UTC, ithqindia requested changes

2022-01-18 14:07 UTC, ithqindia commented on app/Http/Controllers/CounselorSessionController.php
> +
Remove commented code

2022-01-18 14:07 UTC, ithqindia commented on app/Http/Controllers/CounselorSessionController.php
> +
Remove

2022-01-18 14:07 UTC, ithqindia commented on app/Http/Controllers/StudentController.php
> +
Remove

2022-01-18 14:14 UTC, ithqindia requested changes

2022-01-18 14:14 UTC, ithqindia commented on resources/views/me/counselor-session-form.blade.php
> + <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
Not required. It's already included in theme

2022-01-18 14:14 UTC, ithqindia commented on resources/views/me/counselor-session-form.blade.php
> + </script>
move this in scripts section

2022-01-18 15:24 UTC, sumedh-mohod commented on app/Http/Controllers/CounselorSessionController.php
> +
removed

2022-01-18 15:25 UTC, sumedh-mohod commented on app/Http/Controllers/StudentController.php
> +
removed

2022-01-18 15:25 UTC, sumedh-mohod commented on resources/views/me/counselor-session-form.blade.php
> + <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
removed

2022-01-18 15:25 UTC, sumedh-mohod commented on resources/views/me/counselor-session-form.blade.php
> + </script>
moved in script section

2022-01-19 04:57 UTC, ithqindia approved these changes

2022-01-19 08:40 UTC, sumedh-mohod commented
view page done but showing page not found while clicked on view button

2022-01-19 08:58 UTC, ithqindia approved these changes

2022-01-19 09:47 UTC, ithqindia commented
Merged in https://github.com/ithqindia/metroclub/pull/123

2022-01-19 09:47 UTC, closed without merging