Test/dec 20 kajal
ithqindia/metroclub pull request #13
Opened 2021-12-22 12:35 UTC by kkaajjaall

2021-12-22 12:48 UTC, kkaajjaall commented
insert data , update data and view data are done and delete is remain

2021-12-23 12:43 UTC, kkaajjaall commented
delete is done  and Add new data to show session message is remain

2021-12-23 13:07 UTC, ithqindia requested changes
Format files

2021-12-23 13:07 UTC, ithqindia commented on app/Http/Controllers/CourseMajorController.php
> +     $CourseMajor = CourseMajor::get();
Follow naming convention. This should be $courseMajor

2021-12-23 13:07 UTC, ithqindia commented on app/Http/Controllers/CourseMajorController.php
> +    $user = [];
Remove this line

2021-12-23 13:07 UTC, ithqindia commented on app/Http/Controllers/CourseMajorController.php
> +        return view('Course-major-info', compact('course_major'));
follow naming convention course-major-info

2021-12-23 13:07 UTC, ithqindia commented on app/Http/Controllers/CourseMajorController.php
> +        $course_major = CourseMajor::find($request->id);
Follow naming convention

2021-12-23 13:07 UTC, ithqindia commented on app/Models/CourseMajor.php
> +    protected $table='course_majors';
Remove this.

2021-12-23 13:07 UTC, ithqindia commented on routes/web.php
> +});
Remove this. This should be handled in Route::get('/course-major', [CourseMajorController::class, 'index']);

2021-12-27 08:06 UTC, ithqindia requested changes

2021-12-27 08:06 UTC, ithqindia commented on resources/views/course-major-form.blade.php
> +                </div>
</form></div> missing

2021-12-27 08:06 UTC, ithqindia commented on resources/views/course-majors.blade.php
> +        @foreach ($courseMajors as $major_course)
wrong variable name $major_course should be $courseMajor

2021-12-27 08:06 UTC, ithqindia commented on resources/views/includes/sidebar/menu.blade.php
> +            </div>
Correct the link to show course majors

2021-12-27 08:28 UTC, ithqindia requested changes

2021-12-27 08:28 UTC, ithqindia commented on resources/views/includes/sidebar/menu.blade.php
> +                <a class="menu-link" href="/course-majors/add">
this should be /courses

2021-12-27 08:35 UTC, ithqindia approved these changes

2021-12-27 08:35 UTC, ithqindia commented
Merged locally

2021-12-27 08:35 UTC, closed without merging