Test/dec 20 manisha
ithqindia/metroclub pull request #14
Opened 2021-12-22 12:41 UTC by manii283

2021-12-22 12:48 UTC, manii283 commented
insert data, update data, view data is done .
delete is remain

2021-12-23 12:43 UTC, manii283 commented
country id and delete are done.
add new data to show session message is remain.

2021-12-23 13:05 UTC, ithqindia requested changes
Format all files

2021-12-23 13:05 UTC, ithqindia commented on app/Http/Controllers/UniversityController.php
> +       $University = University::get();
Follow naming convention this should be $universities

2021-12-23 13:05 UTC, ithqindia commented on app/Http/Controllers/UniversityController.php
> +       return view('/university', compact('University'));
view name should also be universities

2021-12-23 13:05 UTC, ithqindia commented on app/Http/Controllers/UniversityController.php
> +        $user = [];
remove this line

2021-12-23 13:05 UTC, ithqindia commented on app/Models/University.php
> +    protected $table = "universities";
remove this lines as laravel automatically gets table name based on model name

2021-12-23 13:05 UTC, ithqindia commented on routes/web.php
> +});
This is handled in Route::get('/university', [UniversityController::class, 'index']);
remove these lines

2021-12-24 10:06 UTC, ithqindia requested changes

2021-12-24 10:06 UTC, ithqindia commented on app/Http/Controllers/UniversityController.php
> +        $userInformation = University::find($request->id);
$userInformation  change $university

2021-12-24 10:06 UTC, ithqindia commented on resources/views/show.blade.php
> +            @endphp
Wrong.

2021-12-24 10:06 UTC, ithqindia commented on resources/views/show.blade.php
> +                    <td>{{ $counter }}</td>
This should be $loop->index	https://laravel.com/docs/8.x/blade#the-loop-variable

2021-12-24 10:06 UTC, ithqindia commented on routes/web.php
>  });
Update as per https://ithqworkspace.slack.com/archives/C02NSD7L98W/p1640319747003300

2021-12-24 12:43 UTC, manii283 commented
code is updated but showing some errors in file

2021-12-24 13:05 UTC, ithqindia requested changes

2021-12-24 13:05 UTC, ithqindia commented on routes/web.php
> +Route::get('/universities', function () {
This route is no longer required

2021-12-24 13:05 UTC, ithqindia commented on routes/web.php
> +Route::get('/universities-form', function () {
This route is no longer required

2021-12-27 08:09 UTC, ithqindia requested changes

2021-12-27 08:09 UTC, ithqindia commented on resources/views/includes/sidebar/menu.blade.php
> +            </div>
Extra </div> remove

2021-12-27 08:09 UTC, ithqindia commented on routes/web.php
> +});
Delete these lines

2021-12-27 08:34 UTC, ithqindia commented
Merged locally

2021-12-27 08:34 UTC, closed without merging