code updated and view done
ithqindia/metroclub pull request #15
Opened 2021-12-22 12:51 UTC by sumedh-mohod

data inserted and updated and view done and labales for details and select for university id remain.

2021-12-23 12:43 UTC, sumedh-mohod commented
select option for university id and course major added and deleted funtion added

2021-12-23 13:02 UTC, ithqindia requested changes
Format all files

2021-12-23 13:02 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +        // dd($courseInformation);
Not required. Remove

2021-12-23 13:02 UTC, ithqindia commented on app/Models/Country.php
> +    protected $table = "courses";
Remove this line. Not required as model Country plural is countries hence Laravel automatically gets the table name as countries

2021-12-23 13:02 UTC, ithqindia commented on app/Models/Course.php
> +    protected $table="courses";
Remove

2021-12-23 13:02 UTC, ithqindia commented on routes/web.php
> +});
remove this. It should be handled in Route::get('/courses', [CoursesController::class, 'index']);

2021-12-24 07:56 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +        $course_major = CourseMajor::get()->sortBy('name');
Variable name $courseMajors

2021-12-24 07:59 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +        return view('course-show', compact('courseShow'));
return redirect....

2021-12-24 07:59 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +        $course_major = CourseMajor::get();
$courseMajors

2021-12-24 10:04 UTC, ithqindia requested changes

2021-12-24 10:04 UTC, ithqindia commented on resources/views/course-show.blade.php
> +        @php $counter = 1; @endphp
Wrong

2021-12-24 10:04 UTC, ithqindia commented on resources/views/course-show.blade.php
> +                <td> {{ $counter }}</td>
https://laravel.com/docs/8.x/blade#the-loop-variable

2021-12-24 12:42 UTC, sumedh-mohod commented
code updated but showing some error in form

2021-12-24 13:01 UTC, ithqindia requested changes

2021-12-24 13:01 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +        $courseInformation = Course::find($id);
name it as simple $course

2021-12-24 13:01 UTC, ithqindia commented on routes/web.php
> +Route::get('/courses', function () {
This route is no longer required

2021-12-27 07:52 UTC, ithqindia requested changes

2021-12-27 07:52 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +{
Format this file

2021-12-27 07:52 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +        return redirect('courses', compact('courseShow'));
return redirect('courses');

2021-12-27 07:52 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +    // }
delete these lines

2021-12-27 07:52 UTC, ithqindia commented on resources/views/courses-form.blade.php
> +            </div> --}}
Remove commented code

2021-12-27 07:52 UTC, ithqindia commented on resources/views/includes/sidebar/menu.blade.php
> +            </div>
This is not required

2021-12-27 07:52 UTC, ithqindia commented on routes/web.php
> +});
Delete this

2021-12-27 07:52 UTC, ithqindia commented on routes/web.php
> +// Route::get('/courses/{id}/view', [CoursesController::class, 'view']);
Delete commented line

2021-12-27 08:26 UTC, ithqindia requested changes

2021-12-27 08:26 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +{
This is not done

2021-12-27 08:36 UTC, ithqindia approved these changes

2021-12-27 08:41 UTC, ithqindia commented
Merged locally

2021-12-27 08:41 UTC, closed without merging