updates/kajal-feb-2
ithqindia/metroclub pull request #159
Opened 2022-02-02 09:12 UTC by kkaajjaall

2022-02-02 10:19 UTC, ithqindia approved these changes

2022-02-02 11:56 UTC, ithqindia commented on resources/views/admin/address.blade.php
>                                          <a href="#" class="text-gray-900 text-hover-primary fs-2 fw-bolder me-1">
` <a href="#"` change to `span`

2022-02-02 11:57 UTC, ithqindia commented on resources/views/admin/counselor-session.blade.php
>                          <a class="text-gray-900 text-hover-primary fs-2 fw-b older me-1"> {{ $user->name }}</a>
change to span

2022-02-02 11:57 UTC, ithqindia requested changes
<a class="text-gray-900 text-hover-primary fs-2 fw-b older me-1"> {{ $user->name }}</a>
change all to span tag

2022-02-02 12:11 UTC, kkaajjaall commented
span added

2022-02-02 12:13 UTC, ithqindia approved these changes

2022-02-03 07:04 UTC, ithqindia commented
Merged in https://github.com/ithqindia/metroclub/pull/158

2022-02-03 07:04 UTC, closed without merging