Test/dec 20 vivek
ithqindia/metroclub pull request #16
Opened 2021-12-22 13:00 UTC by vivek1214-git

completed- form update
todo- form not showing ,view page is  not showing and cant redirect to the new form

2021-12-23 12:46 UTC, vivek1214-git commented
completed country form and tag form delete functionality
todo  add new data insert msg functionality remaining.

2021-12-23 12:58 UTC, ithqindia requested changes

2021-12-23 12:58 UTC, ithqindia commented on app/Http/Controllers/CountriesController.php
> +class CountriesController extends Controller
CountryController

2021-12-23 12:58 UTC, ithqindia commented on app/Http/Controllers/CountriesController.php
> +        $countryInformation = Country::get();
$countryInformation instead use $countries

2021-12-23 12:58 UTC, ithqindia commented on app/Http/Controllers/CountriesController.php
> +        //dd(CountryInformation);
Remove these lines

2021-12-23 12:58 UTC, ithqindia commented on app/Http/Controllers/SelfieController.php
> +        Selfies::create([
Check naming conventions https://ithqworkspace.slack.com/archives/C02H79MJNQG/p1640177593015700
Model names should be singular 
Update at all places

2021-12-23 12:58 UTC, ithqindia commented on app/Http/Controllers/TagController.php
> +        //dd(CountryInformation);
remove these lines

2021-12-23 12:58 UTC, ithqindia commented on app/Models/Country.php
> +    protected $table = "Countries";
Remove this line. Not required to specify table name

2021-12-23 12:58 UTC, ithqindia commented on app/Models/Tag.php
> +    protected $table = "tags";
Remove this line. Not required to specify table name

2021-12-23 12:58 UTC, ithqindia commented on database/factories/CounselorSessionFactory.php
> +            //'address2' => $this->faker->address(),
remove this line

2021-12-23 12:58 UTC, ithqindia commented on database/factories/ExtraScoreFactory.php
> +            //'address2' => $this->faker->address(),
remove these lines

2021-12-23 12:58 UTC, ithqindia commented on database/factories/SelfieFactory.php
> +            //'address2' => $this->faker->address(),
remove these lines

2021-12-23 12:58 UTC, ithqindia commented on routes/web.php
> +});
These are not required. 
Following routes do the same thing
Route::get('/tag', [TagController::class, 'index']);
Route::get('/country', [CountriesController::class, 'index']);

2021-12-24 09:58 UTC, ithqindia requested changes

2021-12-24 09:58 UTC, ithqindia commented on app/Http/Controllers/CountryController.php
> +        $country = Country::get();
We are getting all data from Country so the variable would be $countries

2021-12-24 09:58 UTC, ithqindia commented on app/Http/Controllers/CountryController.php
> +        $countries = Country::find($request->id);
Here we are getting single country hence variable $country

2021-12-24 09:58 UTC, ithqindia commented on app/Http/Controllers/CountryController.php
> +        $countries = Country::find($request->id);
Here we are getting single country hence variable $country

2021-12-24 09:58 UTC, ithqindia commented on routes/web.php
> + });
Need to update as per https://ithqworkspace.slack.com/archives/C02H79MJNQG/p1640252019001700

2021-12-24 09:58 UTC, ithqindia commented on routes/web.php
> +
Do not have more than one empty line

2021-12-27 03:40 UTC, ithqindia commented
Amol is managing this branch. Vivek's branch is https://github.com/ithqindia/metroclub/pull/17
both these branches should be merged into develop

2021-12-27 03:40 UTC, closed without merging