kajal/Mar-28
ithqindia/metroclub pull request #169
Opened 2022-03-28 12:30 UTC by kkaajjaall

2022-03-28 12:41 UTC, ithqindia requested changes

2022-03-28 12:41 UTC, ithqindia commented on resources/views/components/diploma-form.blade.php
> +                                message: '  year to is required',
Empty spaces

2022-03-28 12:41 UTC, ithqindia commented on resources/views/components/diploma-form.blade.php
> +                                message: 'Select option is required',
Select option use meaningful message

2022-03-28 12:41 UTC, ithqindia commented on resources/views/components/diploma-form.blade.php
> +                                message: ' year to must have at least 8 characters',
Empty space

2022-03-29 10:14 UTC, ithqindia requested changes

2022-03-29 10:14 UTC, ithqindia commented on resources/views/components/diploma-form.blade.php
> +            value="{{ old('completion_status', $diplomaInformation->completion_status ?? '') }}">
code not formatted

2022-03-29 10:14 UTC, ithqindia commented on resources/views/components/diploma-form.blade.php
> +        @enderror
Wrong formatting

2022-03-29 10:14 UTC, ithqindia commented on resources/views/components/diploma-form.blade.php
> +                                message: 'Diploma year form is required',
form -> from

2022-03-29 10:14 UTC, ithqindia commented on resources/views/components/diploma-form.blade.php
> +                                message: 'Please select the Completion status',
Remove the

2022-03-29 11:10 UTC, ithqindia requested changes

2022-03-29 11:10 UTC, ithqindia commented on resources/views/components/ielts-form.blade.php
> +                            },
TRF

2022-03-29 12:18 UTC, ithqindia requested changes

2022-03-29 12:18 UTC, ithqindia commented on resources/views/components/gre-general-form.blade.php
> +
Empty line

2022-03-29 12:43 UTC, kkaajjaall commented on resources/views/components/gre-general-form.blade.php
> +
at starting i made some changes in this form but now gre-general-form is done by vivek .

2022-03-29 13:12 UTC, ithqindia commented on resources/views/components/gre-general-form.blade.php
> +
That does not matter who has done what, you need to change it.

2022-03-30 05:36 UTC, ithqindia commented
Merged locally

2022-03-30 05:36 UTC, closed without merging