Manisha/mar-28
ithqindia/metroclub pull request #170
Opened 2022-03-28 12:32 UTC by manii283

2022-03-28 12:36 UTC, ithqindia commented on resources/views/me/ssc-form.blade.php
> +        <form class="row g-3" method="post" action="/me/hsc" enctype="multipart/form-data" id='ssc-form'>
❓

2022-03-28 12:36 UTC, ithqindia commented on resources/views/me/ssc-form.blade.php
> +        <form class="row g-3" method="post" action="/me/hsc" enctype="multipart/form-data" id='ssc-form'>
ssc to hsc

2022-03-28 12:37 UTC, ithqindia commented on resources/views/components/graduation-form.blade.php
> +                                message: 'college name must be more than 5 characters long',
Capital C

2022-03-29 09:58 UTC, sumedh-mohod commented on resources/views/components/graduation-form.blade.php
>                                  message: 'Graduation year form is required',
message: year from

2022-03-29 10:12 UTC, ithqindia requested changes

2022-03-29 10:12 UTC, ithqindia commented on resources/views/components/personal-information-form.blade.php
> +        <input type="text" class="form-control @error('email') is-invalid @enderror" name="email" id="email"
explain this change

2022-03-29 10:12 UTC, ithqindia commented on resources/views/components/personal-information-form.blade.php
> +let teenager = moment(new Date());
check formatting - code not aligned

2022-03-29 10:12 UTC, ithqindia commented on resources/views/components/personal-information-form.blade.php
> +                                message: 'The mobile number is required',
Change to - Mobile number is required

2022-03-29 10:12 UTC, ithqindia commented on resources/views/components/personal-information-form.blade.php
> +                    // },
Remove commented code

2022-03-29 10:15 UTC, manii283 commented on resources/views/components/personal-information-form.blade.php
> +        <input type="text" class="form-control @error('email') is-invalid @enderror" name="email" id="email"
red border was not applying while validation that's why I was changed

2022-03-29 10:31 UTC, ithqindia approved these changes

2022-03-30 05:36 UTC, ithqindia commented
Merged locally

2022-03-30 05:36 UTC, closed without merging