vivek/Mar-28
ithqindia/metroclub pull request #171
Opened 2022-03-28 12:36 UTC by vivek1214-git

post-graduation select dropdown validation

2022-03-29 10:20 UTC, ithqindia requested changes
Are you planning to take the test again - I think this is not mandatory and should be set to no by default

2022-03-29 10:20 UTC, ithqindia commented on resources/views/components/duolingo-form.blade.php
> +</div>
code not formatted

2022-03-29 10:20 UTC, ithqindia commented on resources/views/components/duolingo-form.blade.php
> +$("#duolingo_exam_date").daterangepicker({
code not formatted

2022-03-29 10:20 UTC, ithqindia commented on resources/views/components/duolingo-form.blade.php
> +                                message: 'UserId is required',
Duolingo user id is required

2022-03-29 10:20 UTC, ithqindia commented on resources/views/components/gre-general-form.blade.php
> +            @enderror
code not formatted

2022-03-29 10:20 UTC, ithqindia commented on resources/views/components/gre-general-form.blade.php
> +            @enderror
code not formatted

2022-03-29 10:20 UTC, ithqindia commented on resources/views/components/gre-general-form.blade.php
> +        @enderror
code not formatted

2022-03-29 10:20 UTC, ithqindia commented on resources/views/components/gre-general-form.blade.php
> +            <p>Are you planning to take the test again<span style="color:red; font-size:20px">*</span></p>
Is this field required?

2022-03-29 10:39 UTC, vivek1214-git commented on resources/views/components/gre-general-form.blade.php
> +            <p>Are you planning to take the test again<span style="color:red; font-size:20px">*</span></p>
sir I was checked the backend validation so their was required field for this test again field so I was applied on frontend also

2022-03-29 11:15 UTC, ithqindia requested changes
Please check formatting

2022-03-29 13:08 UTC, ithqindia commented on resources/views/me/post-graduation-form.blade.php
> +        <form class="row g-3" method="post" action="/me/hsc" enctype="multipart/form-data" id='post-graduation-form'>
❓

2022-03-30 05:36 UTC, ithqindia commented
Merged locally

2022-03-30 05:36 UTC, closed without merging