sumedh/Mar-28
ithqindia/metroclub pull request #172
Opened 2022-03-28 12:47 UTC by sumedh-mohod

validation

2022-03-28 12:54 UTC, ithqindia requested changes

2022-03-28 12:54 UTC, ithqindia commented on resources/views/components/employment-form.blade.php
> +                                message: 'employer address is required',
E

2022-03-28 12:54 UTC, ithqindia commented on resources/views/components/employment-form.blade.php
> +                                message: 'employer name must be more than 4 characters long',
Wrong message

2022-03-29 09:56 UTC, manii283 commented on resources/views/components/employment-form.blade.php
> +                                message: 'Employer address must be more than 5 characters long and less than 255 characters',
change the msessage

2022-03-29 10:07 UTC, ithqindia commented on resources/views/components/employment-form.blade.php
> +            class="form-select form-control @error('employment_status') is-invalid @enderror" name="employment_status"
Please explain this change.

2022-03-29 10:21 UTC, ithqindia approved these changes

2022-03-30 05:36 UTC, ithqindia commented
Merged locally

2022-03-30 05:36 UTC, closed without merging