error in data inserting
ithqindia/metroclub pull request #2
Opened 2021-12-11 05:26 UTC by kkaajjaall

error in data inserting after submit click.

2021-12-11 05:27 UTC, amolswnz commented on app/Http/Controllers/TestData.php
> +        return $request;
Remove this line

2021-12-13 09:50 UTC, ithqindia requested changes

2021-12-13 09:50 UTC, ithqindia commented on app/Http/Controllers/AddressData.php
> +            'permanent_pincode'=>'required|size:6|digits:6',
remove size requirement

2021-12-13 09:50 UTC, ithqindia commented on app/Http/Controllers/AddressData.php
> +            'permanent_emergancy_contact_name' => $request->get('permanent_emergancy_contact_name'),
correct spelling emergency

2021-12-13 09:50 UTC, ithqindia commented on app/Http/Controllers/EmployeData.php
> +            'employment_end' => 'required|date|after_or_equal:employment_start',
Very good.

2021-12-13 09:50 UTC, ithqindia commented on app/Http/Controllers/LocalAddress.php
> +            'local_add'=>'required|min:10|max:100' ,
local_address

2021-12-13 09:50 UTC, ithqindia commented on app/Http/Controllers/LocalAddress.php
> +            'local_pincode'=>'required|size:6|digits:6',
Remove size

2021-12-13 09:50 UTC, ithqindia commented on app/Http/Controllers/LocalAddress.php
> +            'local_emergancy_contact_name'=>'required',
emergency

2021-12-13 09:50 UTC, ithqindia commented on app/Http/Controllers/RefreeData.php
> +            'organization' => 'required',
organisation - British spelling

2021-12-13 09:50 UTC, ithqindia commented on app/Http/Controllers/LocalAddress.php
> +        Data::create([
Change to LocalData

2021-12-13 09:50 UTC, ithqindia commented on app/Models/Data.php
> +    protected $table = "local_addresses_details";
local_address_details

2021-12-13 09:50 UTC, ithqindia commented on app/Models/Data.php
> +class Data extends Model
LocalData

2021-12-13 09:50 UTC, ithqindia commented on app/Models/EmployeAddress.php
> +    protected $table = "employe_addresses";
employee_addresses

2021-12-13 09:50 UTC, ithqindia commented on database/migrations/2021_12_13_052856_create_local__addresses_table.php
> +        Schema::create('local_addresses_details', function (Blueprint $table) {
local_address_details

2021-12-13 09:50 UTC, ithqindia commented on database/migrations/2021_12_13_052856_create_local__addresses_table.php
> +            $table->string('local_add');
local_address

2021-12-13 09:50 UTC, ithqindia commented on routes/web.php
> +Route::post('/test2', [RefreeData::class, 'store']);
/referee-data

2021-12-13 09:50 UTC, ithqindia commented on routes/web.php
> +Route::post('/test3', [AddressData::class, 'store']);
/address-data

2021-12-13 09:51 UTC, ithqindia commented
Please format all your files and remove empty lines keep it to minimum one empty line.

2021-12-13 09:51 UTC, ithqindia commented
app/Http/Controllers/Exceptions/Handler.php why this file is renamed?

2021-12-13 11:36 UTC, ithqindia commented on app/Http/Controllers/AddressData.php
> +
empty line remove

2021-12-13 11:36 UTC, ithqindia commented on app/Http/Controllers/RefreeData.php
> +
empty line remove

2021-12-13 11:36 UTC, ithqindia commented on app/Http/Controllers/RefreeData.php
> +
empty line remove

2021-12-13 11:36 UTC, ithqindia commented on app/Http/Controllers/RefreeData.php
> +
empty line remove

2021-12-13 11:36 UTC, ithqindia commented on app/Models/EmployeDetails.php
> +class EmployeDetails extends Model
Model name should be singular EmployeDetail not EmployeDetails

2021-12-13 11:36 UTC, ithqindia commented on app/Models/EmployeAddress.php
> +    protected $table = "employe_address";
table names should be plural employe_addresses

2021-12-13 11:36 UTC, ithqindia commented on app/Models/RefereeDetails.php
> +class RefereeDetails extends Model
Model name should be singular

2021-12-13 11:36 UTC, ithqindia commented on database/migrations/2021_12_11_062752_create_details_table.php
> +        Schema::create('employe_details', function (Blueprint $table) {
employee_details

2021-12-13 11:36 UTC, ithqindia commented on database/migrations/2021_12_11_144809_create_addrescess_table.php
> +        Schema::create('employe_address', function (Blueprint $table) {
employee_addresses

2021-12-13 12:41 UTC, ithqindia approved these changes

2021-12-16 12:14 UTC, ithqindia reviewed
Change all controller names. Add Controller at end of name not at start

2021-12-16 12:18 UTC, ithqindia reviewed
Files names and class names needs to changed from Employe to Employee

2021-12-16 12:18 UTC, ithqindia commented on app/Models/EmployeAddress.php
> +class EmployeAddress extends Model
EmployeeAddress

2021-12-16 12:18 UTC, ithqindia commented on app/Models/EmployeDetail.php
> +class EmployeDetail extends Model
EmployeeDetail

2021-12-16 12:18 UTC, ithqindia commented on app/Models/LocalData.php
> +class LocalData extends Model
LocalAddressData

2021-12-16 12:18 UTC, ithqindia commented on app/Models/User.php
> +    public function employe_data()
employee_data

2021-12-16 12:18 UTC, ithqindia commented on app/Models/User.php
> +    public function local_data()
local_address_data

2021-12-16 12:18 UTC, ithqindia commented on app/Models/User.php
> +    public function address_data()
employee_address_data

2021-12-18 05:30 UTC, ithqindia approved these changes

2021-12-18 05:30 UTC, ithqindia commented on resources/views/address-info.blade.php
> +    <h2>User Informatio</h2>
User information

2021-12-20 07:25 UTC, closed without merging