Feature/sumedh
ithqindia/metroclub pull request #4
Opened 2021-12-12 20:01 UTC by sumedh-mohod

file added

2021-12-13 10:08 UTC, ithqindia requested changes
Please format all your files and remove empty lines keep it to minimum one empty line.

2021-12-13 10:08 UTC, ithqindia commented on app/Http/Controllers/TestData.php
> +            'ssc_percentage'=>'required|size:2|digits:2',
Percentage can be in 4/2 digits.
Remove this and instead use `'required|numeric|between:0,99.99',`

2021-12-13 10:08 UTC, ithqindia commented on app/Http/Controllers/TestData1.php
> +class TestData1 extends Controller
TestData1 -> EducationalInformationHsc

2021-12-13 10:08 UTC, ithqindia commented on app/Http/Controllers/TestData2.php
> +            // 'email' => 'required|email',
Remove commented lines

2021-12-13 10:08 UTC, ithqindia commented on app/Http/Controllers/TestData3.php
> +class TestData3 extends Controller
TestData3 -> EducationalInformationDiploma

2021-12-13 10:08 UTC, ithqindia commented on app/Http/Controllers/TestData4.php
> +class TestData4 extends Controller
EducationalInformationPostGraduation

2021-12-13 10:08 UTC, ithqindia commented on app/Models/Post_Graduation.php
> +class Post_Graduation extends Model
Post_Graduation -> PostGraduation

2021-12-13 10:08 UTC, ithqindia commented on database/migrations/2021_12_13_051229_create_ssc.php
> +        Schema::create('ssc', function (Blueprint $table) {
`sscs` We have to following naming convention

2021-12-13 10:08 UTC, ithqindia commented on database/migrations/2021_12_13_060747_create_graduation.php
> +        Schema::create('graduation', function (Blueprint $table) {
graduations

2021-12-13 10:08 UTC, ithqindia commented on database/migrations/2021_12_13_063357_create_diploma.php
> +        Schema::create('diploma', function (Blueprint $table) {
diplomas

2021-12-13 10:08 UTC, ithqindia commented on database/migrations/2021_12_13_065726_create_post_graduation.php
> +        Schema::create('post_graduation', function (Blueprint $table) {
post_graduations

2021-12-13 10:08 UTC, ithqindia commented on database/migrations/2021_12_13_071548_create_hsc.php
> +        Schema::create('hsc', function (Blueprint $table) {
hscs

2021-12-13 10:08 UTC, ithqindia commented on routes/web.php
> +Route::post('/testhsc', [TestData1::class, 'store']);
/hsc-details

2021-12-13 10:09 UTC, ithqindia commented
Please format all your files and remove empty lines keep it to minimum one empty line.

2021-12-13 12:01 UTC, ithqindia commented on app/Models/Diploma.php
> +    protected $table = "diploma";
protected $table = "diplomas";

2021-12-13 12:01 UTC, ithqindia commented on app/Models/Graduation.php
> +    protected $table = "graduation";
protected $table = "graduations";

2021-12-13 12:01 UTC, ithqindia commented on app/Models/Hsc.php
> +    protected $table = "hsc";
protected $table = "hscs";

2021-12-13 12:01 UTC, ithqindia commented on app/Models/Post_Graduation.php
> +    protected $table = "post_graduation";
protected $table = "post_graduations";

2021-12-13 12:01 UTC, ithqindia commented on app/Models/Ssc.php
> +    protected $table = "ssc";
protected $table = "sscs";

2021-12-13 12:32 UTC, ithqindia requested changes

2021-12-13 12:32 UTC, ithqindia commented on app/Models/Post_Graduation.php
> +class Post_Graduation extends Model
Still not done

2021-12-13 12:32 UTC, ithqindia commented on app/Models/Post_Graduation.php
> +class Post_Graduation extends Model
change Post_Graduation -> PostGraduation and change file name PostGraduation.php

2021-12-16 12:09 UTC, amolswnz commented on app/Models/User.php
> +    }
```
    public function ssc_information()
    {
        return $this->hasOne(Ssc::class);
    }

    public function Hsc_information()
    {
        return $this->hasOne(Hsc::class);
    }

    public function graduation_information()
    {
        return $this->hasOne(Graduation::class);
    }

    public function diploma_information()
    {
        return $this->hasOne(Diploma::class);
    }

    public function post_graduation_information()
    {
        return $this->hasOne(PostGraduation::class);
    }
```

2021-12-16 12:10 UTC, ithqindia commented on app/Models/User.php
> +    }
public function ssc_information()
    {
        return $this->hasOne(Ssc::class);
    }

    public function Hsc_information()
    {
        return $this->hasOne(Hsc::class);
    }

    public function graduation_information()
    {
        return $this->hasOne(Graduation::class);
    }

    public function diploma_information()
    {
        return $this->hasOne(Diploma::class);
    }

    public function post_graduation_information()
    {
        return $this->hasOne(PostGraduation::class);
    }

2021-12-16 12:11 UTC, ithqindia commented on app/Http/Controllers/EducationalInformationDiplomaController.php
> +        $user = User::with('user_information')->find($request->id);
$user = User::with('diploma_information')->find($request->id);

2021-12-16 12:11 UTC, ithqindia commented on app/Http/Controllers/EducationalInformationGraduationController.php
> +        $user = User::with('user_information')->find($request->id);
change this as per above comment

2021-12-16 12:11 UTC, ithqindia commented on app/Http/Controllers/EducationalInformationHscController.php
> +        $user = User::with('user_information')->find($request->id);
change this as per above comment

2021-12-16 12:11 UTC, ithqindia commented on app/Http/Controllers/EducationalInformationPostgraduationController.php
> +        $user = User::with('user_information')->find($request->id);
change this as per above comment

2021-12-16 12:11 UTC, ithqindia commented on app/Http/Controllers/EducationalInformationSscController.php
> +        $user = User::with('user_information')->find($request->id);
change this as per above comment

2021-12-18 05:31 UTC, ithqindia approved these changes

2021-12-20 05:40 UTC, manii283 commented on resources/views/diploma-info.blade.php
> +                    <lable class="col-lg-4 fw-bold text-muted">College Name</lable>
make the 2nd letter in lower case

2021-12-20 07:24 UTC, closed without merging