mat and toefl forms are done
ithqindia/metroclub pull request #46
Opened 2022-01-07 09:23 UTC by kkaajjaall

2022-01-07 09:45 UTC, ithqindia requested changes

2022-01-07 09:45 UTC, ithqindia commented on resources/views/extra-score-mat-form.blade.php
> +        <x-mat-form :extraScoreMat="extraScoreMat" />
`        <x-mat-form :extraScoreMat="$extraScoreMat" />
`

2022-01-07 09:45 UTC, ithqindia commented on resources/views/extra-score-toefl-form.blade.php
> +            <x-toefl-form :extraScoreToefl="extraScoreToefl" />
`            <x-toefl-form :extraScoreToefl="$extraScoreToefl" />
`

2022-01-07 09:47 UTC, kkaajjaall commented on resources/views/extra-score-mat-form.blade.php
> +        <x-mat-form :extraScoreMat="extraScoreMat" />
couldn't understand the changes

2022-01-08 06:33 UTC, ithqindia commented
Merged locally

2022-01-08 06:33 UTC, closed without merging