file added
ithqindia/metroclub pull request #5
Opened 2021-12-15 14:37 UTC by vivek1214-git

file added

2021-12-16 05:19 UTC, kkaajjaall commented on app/Http/Controllers/DataTest.php
> +             'meeting_name' => 'required',
remove the extra space

2021-12-16 05:20 UTC, kkaajjaall commented on app/Http/Controllers/DataTest.php
> +            // 'email' => 'required|email',
remove the comment lines

2021-12-16 05:22 UTC, kkaajjaall commented on app/Http/Controllers/Selfie.php
> +            // 'phone' => 'required|size:10|digits:10',
remove comment lines

2021-12-16 06:39 UTC, kkaajjaall commented on app/Http/Controllers/Selfie.php
change your file name
Selfie->SelfieController

2021-12-16 06:39 UTC, kkaajjaall commented on app/Http/Controllers/TestData.php
>  }
change file name
TestData->ExtraScoredController

2021-12-16 06:39 UTC, kkaajjaall commented on app/Models/ExamForm.php
> +}
change model name
ExamForm->ExtraScored

2021-12-16 06:39 UTC, kkaajjaall commented on app/Models/Form.php
> +}
change model name
Form->CounselorSession

2021-12-16 06:39 UTC, kkaajjaall commented on resources/views/counselorsession.blade.php
> +                <input type="date" class="form-control @error('session_date') is-invalid @enderror" name="session_date" id="inputDate"  value="{{ old('session_date') }}">
all id should be meaning full

2021-12-16 06:39 UTC, kkaajjaall commented on routes/web.php
> +Route::post('/test3', [Selfie::class, 'store']);
format all the file and remove extra space

2021-12-16 12:25 UTC, ithqindia commented on app/Http/Controllers/CounselorSessionController.php
> +        CounselorSessionModel::create([
This should be CounselorSession

2021-12-16 12:25 UTC, ithqindia commented on app/Models/CounselorSessionModel.php
> +class CounselorSessionModel extends Model
CounselorSession

2021-12-16 12:25 UTC, ithqindia commented on app/Models/CounselorSessionModel.php
> +    protected $table = "counselorsessions";
counselor_sessions

2021-12-16 12:25 UTC, ithqindia commented on app/Models/ExtraScore.php
> +    protected $table = "extrascores";
extra_scores

2021-12-16 12:25 UTC, ithqindia commented on database/migrations/2021_12_15_182433_create_formdata.php
> +        Schema::create('counselorsessions', function (Blueprint $table) {
counselors_sessions

2021-12-16 12:25 UTC, ithqindia commented on database/migrations/2021_12_15_191651_create_examform.php
> +        Schema::create('extrascores', function (Blueprint $table) {
exra_scores

2021-12-16 12:25 UTC, ithqindia commented on database/migrations/2021_12_16_080643_add_user_id.php
> +            $table->unsignedBigInteger('user_id');
Changes these too

2021-12-16 12:25 UTC, ithqindia commented on dropColumn('user_id')
> +  Too many arguments to "make:migration" command, expected arguments "name".
Delete this file

2021-12-16 12:25 UTC, ithqindia commented on resources/views/counselorsession.blade.php
> +            {{-- error code takjoooooooooooooooooooo --}}
Remove this comment

2021-12-16 12:25 UTC, ithqindia commented on resources/views/counselorsession.blade.php
> +            if ($('#input_Radio').is(":checked")) {
input_Radio change to something meaningful

2021-12-16 12:25 UTC, ithqindia commented on resources/views/extrascore.blade.php
> +        <form class="row row-cols-lg-auto g-3 align-items-center" method="post" action="/test">
change action to meaningful

2021-12-16 12:25 UTC, ithqindia commented on resources/views/extrascore.blade.php
> +                    {{-- value =1 kadjooooo ani barobar nav takjoooooooooooooooooo --}}
remove comment

2021-12-16 12:25 UTC, ithqindia commented on routes/web.php
> +Route::get('/counselorsession', function () {
counselor-session

2021-12-16 12:25 UTC, ithqindia commented on routes/web.php
> +    return view('counselorsession');
counselor-session

2021-12-16 12:25 UTC, ithqindia commented on routes/web.php
> +Route::get('/extrascore', function () {
extra-scores

2021-12-16 12:25 UTC, ithqindia commented on routes/web.php
> +    return view('extrascore');
extra-scores

2021-12-16 12:25 UTC, ithqindia commented on routes/web.php
> +Route::get('/counselorsession', function () {
counselor-session

2021-12-16 12:25 UTC, ithqindia commented on routes/web.php
> +    return view('counselorsession', compact('users'));
counselor-session

2021-12-16 12:25 UTC, ithqindia commented on routes/web.php
> +Route::get('/extrascore', function () {
extra-score

2021-12-16 12:25 UTC, ithqindia commented on routes/web.php
> +    return view('extrascore', compact('users'));
extra-score

2021-12-16 12:25 UTC, ithqindia commented on routes/web.php
> +Route::post('/test3', [SelfieController::class, 'store']);
change routes names to meanigful

2021-12-17 12:38 UTC, amolswnz commented on app/Http/Controllers/CounselorSessionController.php
> +        $userInformation->session_time = $request->get('meeting_name');
This should be 
`$userInformation->meeting_name = $request->get('meeting_name');`

2021-12-17 12:45 UTC, ithqindia requested changes

2021-12-17 12:45 UTC, ithqindia commented on app/Models/CounselorSession.php
> +    protected $table = "counselors";
protected $table = "counselor_sessions";
why you changed this

2021-12-17 12:45 UTC, ithqindia commented on database/migrations/2021_12_17_110515_create_counselor_sessions.php
> +        Schema::create('counselors', function (Blueprint $table) {
Schema::create('counselor_sessions', function (Blueprint $table) {
change this

2021-12-17 12:45 UTC, ithqindia commented on database/migrations/2021_12_17_110515_create_counselor_sessions.php
> +        Schema::dropIfExists('counselors');
Schema::dropIfExists('counselor_sessions');
change this

2021-12-17 12:45 UTC, ithqindia commented on database/migrations/2021_12_17_112501_add_user_id.php
> +        Schema::table('counselors', function ($table) {
Schema::table('counselor_sessions', function ($table) {
change

2021-12-17 12:45 UTC, ithqindia commented on resources/views/counselor-session.blade.php
> +                    <input class="form-check-input" type="radio" name="meeting_name" id="gridRadios" value="online">
meaningful name

2021-12-17 12:45 UTC, ithqindia commented on resources/views/counselor-session.blade.php
> +                    <input class="form-check-input" type="radio" name="meeting_name" id="gridRadio" value="offline">
meaningful name

2021-12-17 12:45 UTC, ithqindia commented on resources/views/counselor-session.blade.php
> +        if ($('#gridRadios').is(":checked")) {
meaningful name

2021-12-18 05:29 UTC, ithqindia approved these changes

2021-12-18 10:11 UTC, ithqindia approved these changes
Nice job

2021-12-20 06:10 UTC, manii283 commented on resources/views/counselor-session-info.blade.php
> +                    <lable class="col-lg-4 fw-bold text-muted">Session Type</lable>
change 2nd word in lower case

2021-12-20 06:11 UTC, manii283 commented on resources/views/counselor-session-info.blade.php
> +@endsection
format the code

2021-12-20 06:12 UTC, manii283 commented on resources/views/counselor-session.blade.php
>              <legend class="col-form-label col-sm-2 pt-0">Session Type</legend>
change the 2nd word in lower case

2021-12-20 06:16 UTC, manii283 commented on resources/views/extra-score-info.blade.php
> +                    <lable class="col-lg-4 fw-bold text-muted">Exam Date </lable>
change 2nd word in lower case

2021-12-20 06:16 UTC, manii283 commented on resources/views/extra-score-info.blade.php
> +@endsection
format code code

2021-12-20 06:16 UTC, manii283 commented on resources/views/selfie-info.blade.php
> +                <div class="row mb-7">
remove extra space

2021-12-20 06:16 UTC, manii283 commented on resources/views/selfie.blade.php
> +        <button type="submit" class="btn btn-primary">Upload Image</button>
change the 2nd word in lower case

2021-12-20 07:24 UTC, closed without merging