updates/jan-13-kajal
ithqindia/metroclub pull request #99
Opened 2022-01-13 07:49 UTC by kkaajjaall

2022-01-13 08:00 UTC, ithqindia requested changes

2022-01-13 08:00 UTC, ithqindia commented on routes/web.php
> +                Route::get('/search/courseMajors', [CoursesController::class, 'search']);
courseMajors -> course-majors

2022-01-13 08:00 UTC, ithqindia commented on app/Http/Controllers/CoursesController.php
> +use App\Models\User;
Remove this

2022-01-13 12:41 UTC, kkaajjaall commented
date picker is remain for ielts form

2022-01-14 07:30 UTC, ithqindia approved these changes

2022-01-14 12:18 UTC, ithqindia commented
Merged locally in https://github.com/ithqindia/metroclub/pull/97

2022-01-14 12:18 UTC, closed without merging